#!/usr/bin/env ruby
# frozen_string_literal: true

require 'migration_signature'
require 'optparse'

OptionParser.new do |parser|
  parser.banner = <<~BANNER
    Usage: migration_signature {check}

        check        - Check all your migration files for present and correct migration signatures

  BANNER

  parser.on('-h', '--help', 'Prints this help') do
    puts parser
    exit
  end
end.parse!

action = ARGV[0]
unless action
  warn 'You must supply one of {check}'
  exit 1
end

if action == 'check'
  begin
    MigrationSignature.check_all
  rescue MigrationSignature::InvalidSignatureError => e
    warn e.message
    exit 1
  end
else
  warn 'You must supply one of {check}'
  exit 1
end
